# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lsmod <- function() {
    .Call(`_rgprof_lsmod`)
}

checkmod <- function(fname) {
    .Call(`_rgprof_checkmod`, fname)
}

control <- function(v) {
    invisible(.Call(`_rgprof_control`, v))
}

prof_stop <- function() {
    .Call(`_rgprof_prof_stop`)
}

prof_start <- function(fname) {
    .Call(`_rgprof_prof_start`, fname)
}

