# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' get list of loaded modules inside current process
#'
#'@return string vector of modules with full paths
lsmod <- function() {
    .Call(`_rgprof_lsmod`)
}

#' get frame of loaded modules inside current process
#'
#'@return frame consisted of modules full paths, base address and size
lsmodf <- function() {
    .Call(`_rgprof_lsmodf`)
}

#' get frame of loaded modules inside current process matching regex
#'
#'@param re regex
#'@return frame consisted of modules full paths, base address and size
lsmodfr <- function(re) {
    .Call(`_rgprof_lsmodfr`, re)
}

#' get list of loaded modules inside current process matching regex
#'
#'@param re regex
#'@return string vector of modules with full paths
lsmodr <- function(re) {
    .Call(`_rgprof_lsmodr`, re)
}

#' check if module can be profiles
#'
#'@param fname full path to module
#'@return -1 if no such module or it is not ELF, 0 when module cannot be profiles, 1 if it was conpuled with -pg option, 2 fir -finstrument-functions option
checkmod <- function(fname) {
    .Call(`_rgprof_checkmod`, fname)
}

#'Suspend or resume profiling. Actually this is just wrapper on (undocumented) function moncontrol
#'
#'@param v 0 to suspend, 1 to resume
control <- function(v) {
    invisible(.Call(`_rgprof_control`, v))
}

#'Stop profiling. results will be saved in current directory in file gmon.base_address_of_module.PID
#'
#'@return 0 when no profiling happened, 1 otherwise
prof_stop <- function() {
    .Call(`_rgprof_prof_stop`)
}

#'Start profiling of some module
#'
#'@param fname full path to module
#'@return -1 if no such module or it is not ELF, 0 when module cannot be profiles, 1 if it was conpuled with -pg option, 2 fir -finstrument-functions option
prof_start <- function(fname) {
    .Call(`_rgprof_prof_start`, fname)
}

